-- =====================================================================
-- Migration 0001 — the whole schema
-- =====================================================================
--
-- WHAT A MIGRATION IS
-- A database starts empty. A migration is a numbered file of instructions that
-- builds its structure. They are applied in order, once each, and never edited
-- after they have run anywhere real — because then two copies of the database
-- would silently differ, which is far harder to diagnose than an error.
--
-- To add a column later, write 0002. Do not edit this file.
--
-- HOW DATA IS PROTECTED HERE
-- Passwords are hashed with Argon2id and are never recoverable by anybody.
-- Everything else is stored as ordinary readable values, and is protected by
-- the layers around the database: TLS on the connection, a firewall limiting
-- who can reach it, a database user with only the rights it needs, and the
-- provider's encryption of the underlying disks.
--
-- The practical consequence, stated plainly: **anyone who can query this
-- database can read email addresses and conversations.** Treat the database
-- credentials with the same care as a password. See docs/SECURITY.md.
--
-- CONVENTIONS
--   BINARY(16)   a UUID stored compactly as 16 raw bytes rather than 36 chars
--   DATETIME(6)  a timestamp with microseconds, ALWAYS stored in UTC
--   ON DELETE CASCADE  when a row goes, everything belonging to it goes too,
--                      so deleting an account cannot leave orphans behind
-- =====================================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- ---------------------------------------------------------------------
-- schema_migrations — bookkeeping so the runner knows what has been applied
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS schema_migrations (
  version     VARCHAR(64) NOT NULL COMMENT 'Migration file number, e.g. 0001',
  applied_at  DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'When it ran, UTC',
  checksum    CHAR(64)    NOT NULL COMMENT 'SHA-256 of the file, so edits to applied migrations are caught',
  PRIMARY KEY (version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------------------------------------------------------------------
-- users — one row per account
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  user_id             BINARY(16)   NOT NULL COMMENT 'Random UUIDv4. Random rather than counting, so identifiers reveal nothing and cannot be guessed in sequence.',
  username            VARCHAR(32)  NOT NULL COMMENT 'Public handle.',
  display_name        VARCHAR(64)  NOT NULL COMMENT 'Name shown in the interface.',
  email               VARCHAR(254) NOT NULL COMMENT 'Stored lowercased and trimmed, so one person cannot register twice with different capitalisation.',
  email_verified      TINYINT(1)   NOT NULL DEFAULT 0,
  password_hash       VARCHAR(255) NOT NULL COMMENT 'Argon2id digest, including its own salt and parameters. The password itself is NEVER stored, in any form, and cannot be recovered — only compared against a fresh guess.',
  status              ENUM('active','suspended') NOT NULL DEFAULT 'active',
  failed_login_count  INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Drives lockout after repeated failures.',
  created_at          DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at          DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (user_id),
  UNIQUE KEY uq_users_username (username),
  UNIQUE KEY uq_users_email (email),
  KEY idx_users_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='Accounts.';

-- ---------------------------------------------------------------------
-- campaigns — one ongoing story
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS campaigns (
  campaign_id  BINARY(16)    NOT NULL,
  user_id      BINARY(16)    NOT NULL COMMENT 'Owner.',
  title        VARCHAR(120)  NOT NULL,
  premise      VARCHAR(2000) NULL COMMENT 'Optional opening situation.',
  ruleset      ENUM('dnd5e','freeform') NOT NULL DEFAULT 'dnd5e',
  tone         ENUM('heroic','gritty','comedic','horror','mystery') NOT NULL DEFAULT 'heroic',
  status       ENUM('active','archived') NOT NULL DEFAULT 'active',
  created_at   DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at   DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (campaign_id),
  KEY idx_campaigns_user (user_id, status, updated_at),
  CONSTRAINT fk_campaigns_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------------------------------------------------------------------
-- characters — player characters
--
-- The sheet is stored as JSON rather than as thirty columns. Character sheets
-- gain fields constantly, and a JSON column absorbs that without a migration
-- every time. The fields that are queried — class and level — are real columns.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS characters (
  character_id  BINARY(16)   NOT NULL,
  campaign_id   BINARY(16)   NOT NULL,
  user_id       BINARY(16)   NOT NULL COMMENT 'Owner, stored here too so a character can be checked without a join.',
  name          VARCHAR(64)  NOT NULL,
  sheet         JSON         NOT NULL COMMENT 'Abilities, inventory, backstory, notes.',
  char_class    ENUM('barbarian','bard','cleric','druid','fighter','monk',
                     'paladin','ranger','rogue','sorcerer','warlock','wizard') NOT NULL,
  char_level    TINYINT UNSIGNED NOT NULL DEFAULT 1,
  created_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (character_id),
  KEY idx_characters_campaign (campaign_id),
  KEY idx_characters_user (user_id),
  CONSTRAINT fk_characters_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(campaign_id) ON DELETE CASCADE,
  CONSTRAINT fk_characters_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------------------------------------------------------------------
-- game_sessions — one sitting at the table
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS game_sessions (
  game_session_id  BINARY(16)   NOT NULL,
  campaign_id      BINARY(16)   NOT NULL,
  user_id          BINARY(16)   NOT NULL,
  started_at       DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  ended_at         DATETIME(6)  NULL COMMENT 'NULL while play is in progress.',
  turn_count       INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (game_session_id),
  KEY idx_gs_campaign (campaign_id, started_at),
  KEY idx_gs_user (user_id),
  CONSTRAINT fk_gs_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(campaign_id) ON DELETE CASCADE,
  CONSTRAINT fk_gs_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------------------------------------------------------------------
-- messages — the transcript
--
-- `seq` numbers the messages within a session, and the unique key on
-- (game_session_id, seq) is what stops two simultaneous requests both claiming
-- position 7 and losing one of them.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS messages (
  message_id       BINARY(16)   NOT NULL,
  game_session_id  BINARY(16)   NOT NULL,
  user_id          BINARY(16)   NOT NULL,
  seq              INT UNSIGNED NOT NULL COMMENT 'Position in the conversation: 1, 2, 3...',
  role             ENUM('player','dungeon_master','system') NOT NULL,
  content          MEDIUMTEXT   NOT NULL COMMENT 'What was actually said.',
  input_mode       ENUM('typed','voice') NOT NULL DEFAULT 'typed',
  token_count      INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Length in AI tokens, for cost tracking.',
  created_at       DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (message_id),
  UNIQUE KEY uq_messages_session_seq (game_session_id, seq),
  KEY idx_messages_user (user_id),
  CONSTRAINT fk_messages_session FOREIGN KEY (game_session_id) REFERENCES game_sessions(game_session_id) ON DELETE CASCADE,
  CONSTRAINT fk_messages_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------------------------------------------------------------------
-- analytics_events — how the product is used
--
-- Note what this table cannot hold: there is no free-text column. Every field
-- is an enumerated value, a number or a timestamp. That is deliberate — it
-- means a careless change later cannot start recording what players typed,
-- because there is nowhere for it to go.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics_events (
  event_id        BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id         BINARY(16)      NULL COMMENT 'NULL once the account is deleted, leaving the event as an anonymous contribution to the totals.',
  event_name      ENUM('session_started','session_ended','turn_taken','voice_input_used',
                       'campaign_created','character_created','character_updated',
                       'settings_changed','error_occurred','quota_exhausted',
                       'signup_completed','login_succeeded') NOT NULL,
  occurred_at     DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  country_code    CHAR(2)         NULL COMMENT 'Supplied by the edge network. Country only, never a city or an address.',
  duration_bucket ENUM('lt_1m','1_5m','5_15m','15_30m','30_60m','gt_60m') NULL,
  turn_count      INT UNSIGNED    NULL,
  feature         ENUM('voice_input','typed_input','character_sheet','campaign_list',
                       'dice_roller','settings') NULL,
  error_category  ENUM('validation','rate_limited','upstream_ai','upstream_timeout',
                       'auth','internal') NULL,
  success         TINYINT(1)      NULL,
  PRIMARY KEY (event_id),
  KEY idx_ae_name_time (event_name, occurred_at),
  KEY idx_ae_time (occurred_at),
  KEY idx_ae_user (user_id),
  CONSTRAINT fk_ae_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='Usage counts. ON DELETE SET NULL keeps the totals correct when an account goes.';

INSERT INTO schema_migrations (version, checksum)
VALUES ('0001', 'set-by-migration-runner')
ON DUPLICATE KEY UPDATE applied_at = applied_at;
