/**
 * The in-app disclosure: what happens to what you type.
 *
 * WHY THIS SCREEN EXISTS
 * The project brief requires "a plain-language in-app disclosure so users
 * understand where their words go". This is it.
 *
 * It is not a privacy policy. A privacy policy is a legal document nobody
 * reads. This is a short, honest account of what actually happens, written for
 * someone who has never thought about where their words go and has no reason
 * to. The most important section is the one about Google, because that is the
 * one place where personal data genuinely leaves our control by design — and a
 * disclosure that buried it would be worse than none at all.
 */

import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';

import { APP_CONFIG } from '../../core/app-config';
import { Banner } from '../../shared/ui/banner';

@Component({
  selector: 'app-privacy-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink, Banner],
  template: `
    <div class="page page--narrow">
      <header class="page__header">
        <h1>Your data</h1>
        <p class="page__lead">
          What is stored, what leaves this service, and what you can do about it. In plain
          language, with nothing left out because it was awkward.
        </p>
      </header>

      @if (isLocal()) {
        <app-banner kind="warning" title="This is a development build">
          <p style="margin: 0">
            Encryption is using a key that is written down in a configuration file, sign-in
            is not implemented, and everything is stored in memory and lost on restart.
            Nothing here is protecting anything real yet.
          </p>
        </app-banner>
      }

      <section class="card">
        <h2>The short version</h2>
        <ul class="plain">
          <li>
            <strong>What you type is sent to Google</strong> to generate the Dungeon Master's
            replies. On the free tier, Google may use it to improve their products, and
            their staff may read it.
          </li>
          <li>
            <strong>Voice recordings are not.</strong> They are transcribed on our own
            server and then discarded.
          </li>
          <li>
            <strong>Everything stored is encrypted</strong> with a key belonging only to
            you. Someone who stole the entire database could not read any of it.
          </li>
          <li>
            <strong>Deleting your account really deletes it</strong>, including from
            backups, and cannot be undone by anyone.
          </li>
        </ul>
      </section>

      <section class="card">
        <h2>What is sent to Google, and why that matters</h2>
        <p>
          The Dungeon Master's replies are generated by Google Gemini. To do that, the words
          you type have to be sent to Google. There is no way around this — it is what makes
          the game work.
        </p>
        <p>
          <strong>On the free plan, Google's own terms say they use what is submitted to
          improve their products, and that human reviewers may read it.</strong> Google says
          it disconnects that content from the account it came from first, and advises not
          to send sensitive or personal information.
        </p>
        <p>Two things are done about this:</p>
        <ul class="plain">
          <li>
            <strong>Before anything is sent, it is scrubbed.</strong> Email addresses, phone
            numbers, card numbers, postcodes, web links and dates of birth are replaced with
            a description, so the story still makes sense but the detail never leaves.
          </li>
          <li>
            <strong>You are being told, here, before you type.</strong>
          </li>
        </ul>
        <p>
          What the scrubbing <em>cannot</em> catch is a name in an ordinary sentence — "my
          sister Emma is coming over" looks exactly like naming a character. So the honest
          advice is simple: treat what you type here as something a stranger might read one
          day, and keep genuinely private details out of it.
        </p>
      </section>

      <section class="card">
        <h2>Why speaking is different from typing</h2>
        <p>
          Most applications use the speech recognition built into your browser. In Chrome,
          that works by sending the sound from your microphone to Google.
        </p>
        <p>
          This one does not. Recordings are sent to our own server, turned into text by
          software running there, and then discarded. They are never written to disk and
          never passed to anyone else.
        </p>
        <p class="small muted" style="margin-bottom: 0">
          The reasoning: text can be scrubbed of details before it is sent. A recording of
          your voice cannot — it identifies you regardless of the words in it, and it
          carries whatever else was audible in the room.
        </p>
      </section>

      <section class="card">
        <h2>How your data is stored</h2>
        <p>
          Your email address, your campaign titles, your characters' names and backstories,
          and every message in every conversation are encrypted before they are written
          down, using a key that exists only for your account.
        </p>
        <p>
          The practical meaning: if somebody stole a complete copy of the database — a
          leaked backup, a compromised server, a dishonest administrator — they would find
          your username and nothing else they could read. Not your email, not your name, not
          a single word you wrote.
        </p>
        <p class="small muted" style="margin-bottom: 0">
          Your password is not stored at all, in any form. What is kept is a one-way
          fingerprint that can be checked against a guess but never turned back into a
          password.
        </p>
      </section>

      <section class="card">
        <h2>What is recorded about how you use it</h2>
        <p>
          Counts, and nothing else: sessions started, turns taken, whether voice was used,
          which country the request came from. These are recorded against a random
          identifier that has no connection to your account.
        </p>
        <p>
          There is no field anywhere in that part of the system capable of holding free
          text, so nothing you have written can end up in it — not by accident, and not by a
          careless change later.
        </p>
        <p class="small muted" style="margin-bottom: 0">
          You can switch this off entirely in <a routerLink="/settings">Settings</a>.
        </p>
      </section>

      <section class="card">
        <h2>If we ever need to look at your data</h2>
        <p>
          Reading a user's records to debug a problem is not something that happens casually
          here. Ordinarily, faults are investigated using an identifier attached to a single
          request — which is why error messages show you one to quote.
        </p>
        <p>
          If your data genuinely does need to be decrypted, it requires a stated reason, it
          expires after an hour, it is recorded permanently, and
          <strong>an entry appears in your own
          <a routerLink="/account">account activity</a></strong> saying that it happened and
          why. If we look, you are told.
        </p>
      </section>

      <section class="card">
        <h2>Deleting your account</h2>
        <p>
          Deleting your account destroys the encryption key. Everything belonging to you
          becomes permanently unreadable at that moment — in the live system and in every
          backup, including old ones that cannot be edited.
        </p>
        <p>
          This is genuinely irreversible. Not "deleted and recoverable for thirty days".
          Nobody, including the people running this service, can bring it back.
        </p>
        <p style="margin-bottom: 0">
          <a routerLink="/account">Delete your account</a>
        </p>
      </section>

      <section class="card">
        <h2>What this does not protect against</h2>
        <p>
          Being straight about the limits, because a security promise with unstated
          exceptions is not a promise:
        </p>
        <ul class="plain">
          <li>
            The encryption protects against someone who obtains the stored data. It does not
            protect against someone who takes over the running server itself, because that
            server necessarily holds the keys while it is working.
          </li>
          <li>
            Once your words have been sent to Google, they are subject to Google's terms,
            not ours.
          </li>
          <li>
            Someone with a copy of the database can tell that two accounts share an email
            address, without being able to tell what it is.
          </li>
        </ul>
      </section>
    </div>
  `,
  styles: [
    `
      .page--narrow {
        max-width: 680px;
      }
      section {
        margin-bottom: var(--space-4);
      }
      .plain {
        padding-left: var(--space-5);
        margin: 0 0 var(--space-4);
      }
      .plain li {
        margin-bottom: var(--space-2);
      }
      p,
      li {
        max-width: var(--measure);
      }
    `,
  ],
})
export class PrivacyPage {
  private readonly config = inject(APP_CONFIG);

  /**
   * True when this is not a production build.
   *
   * Drives the warning at the top. Someone reading a page about how carefully
   * their data is protected deserves to be told when they are looking at a
   * development build where none of it is switched on.
   *
   * @returns Whether this build is pointed at production.
   */
  isLocal(): boolean {
    return this.config.environment !== 'production';
  }
}
