/**
 * The in-app disclosure: what happens to what you type.
 *
 * WHY THIS SCREEN EXISTS
 * One thing about this application genuinely deserves to be said out loud
 * before somebody uses it: their words are sent to Google, and on the free
 * plan Google's terms allow them to be used for training and read by human
 * reviewers.
 *
 * This is not a privacy policy — those are legal documents nobody reads. It is
 * a short, honest account of what actually happens, written for someone who
 * has never thought about where their words go.
 */

import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';

import { APP_CONFIG } from '../../core/app-config';
import { Banner } from '../../shared/ui/banner';

@Component({
  selector: 'app-privacy-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink, Banner],
  template: `
    <div class="page page--narrow">
      <header class="page__header">
        <h1>Your data</h1>
        <p class="page__lead">
          What is stored, what leaves this service, and what you can do about it — in plain
          language, with nothing left out because it was awkward.
        </p>
      </header>

      @if (isLocal()) {
        <app-banner kind="warning" title="This is a development build">
          <p style="margin: 0">
            Sign-in is not implemented, and everything may be stored in memory and lost when
            the server restarts. Do not put anything real into it.
          </p>
        </app-banner>
      }

      <section class="card">
        <h2>The short version</h2>
        <ul class="plain">
          <li>
            <strong>What you type is sent to Google</strong> to generate the Dungeon
            Master's replies. On the free plan, Google may use it to improve their products,
            and their staff may read it.
          </li>
          <li>
            <strong>Voice recordings are not.</strong> They are turned into text on our own
            server and then discarded.
          </li>
          <li>
            <strong>Your password is never stored</strong>, in any form. Not even we can see
            it.
          </li>
          <li>
            <strong>Deleting your account really deletes it</strong> — every campaign,
            character and conversation, with no way back.
          </li>
        </ul>
      </section>

      <section class="card">
        <h2>What is sent to Google, and why it matters</h2>
        <p>
          The Dungeon Master's replies are generated by Google Gemini. To do that, the words
          you type have to be sent to Google. There is no way around it — it is what makes
          the game work.
        </p>
        <p>
          <strong>On the free plan, Google's own terms say they use what is submitted to
          improve their products, and that human reviewers may read it.</strong> Google says
          it disconnects that content from the account it came from first, and advises not
          to send sensitive or personal information.
        </p>
        <p>
          The honest advice that follows: <strong>treat what you type here as something a
          stranger might read one day.</strong> Enjoy the game, name your characters
          whatever you like, and keep genuinely private details out of it.
        </p>
      </section>

      <section class="card">
        <h2>Why speaking is different from typing</h2>
        <p>
          Most applications use the speech recognition built into your browser. In Chrome,
          that works by sending the sound from your microphone to Google.
        </p>
        <p>
          This one does not. Recordings go to our own server, are turned into text by
          software running there, and are then discarded. They are never written to disk and
          never passed to anyone else.
        </p>
        <p class="small muted" style="margin-bottom: 0">
          The reasoning: text can be reviewed before it is sent. A recording of your voice
          cannot — it identifies you regardless of the words in it, and it carries whatever
          else was audible in the room.
        </p>
      </section>

      <section class="card">
        <h2>How your data is stored</h2>
        <p>
          Your account, campaigns, characters and conversations are stored in a database.
          They are kept behind a firewall, reached only over an encrypted connection, and
          the disks they sit on are encrypted by the hosting provider.
        </p>
        <p>
          <strong>Being straightforward about the limit:</strong> someone with access to
          that database could read your email address and your conversations. The
          protection is that very few people can reach it, not that the contents are
          scrambled.
        </p>
        <p style="margin-bottom: 0">
          Your password is the exception. It is stored as a one-way fingerprint using
          Argon2id — there is no way to turn it back into your password, for an attacker or
          for us. That is why a forgotten password is reset rather than looked up.
        </p>
      </section>

      <section class="card">
        <h2>What is recorded about how you use it</h2>
        <p>
          Counts, and nothing else: sessions started, turns taken, whether voice was used,
          which country the request came from. There is no field anywhere in that part of
          the system capable of holding free text, so nothing you have written can end up in
          it — not by accident, and not through a careless change later.
        </p>
        <p class="small muted" style="margin-bottom: 0">
          You can switch this off entirely in <a routerLink="/settings">Settings</a>.
        </p>
      </section>

      <section class="card">
        <h2>Deleting your account</h2>
        <p>
          Deleting your account removes it, along with every campaign, character and
          conversation. It is not a flag or a hidden state — the rows are gone.
        </p>
        <p>
          <strong>One honest limitation:</strong> database backups taken before you deleted
          your account still contain your data until they age out of the backup schedule.
          That is true of essentially every online service, and it is worth knowing rather
          than glossing over.
        </p>
        <p style="margin-bottom: 0">
          <a routerLink="/account">Delete your account</a>
        </p>
      </section>
    </div>
  `,
  styles: [
    `
      .page--narrow {
        max-width: 680px;
      }
      section {
        margin-bottom: var(--space-4);
      }
      .plain {
        padding-left: var(--space-5);
        margin: 0 0 var(--space-4);
      }
      .plain li {
        margin-bottom: var(--space-2);
      }
      p,
      li {
        max-width: var(--measure);
      }
    `,
  ],
})
export class PrivacyPage {
  private readonly config = inject(APP_CONFIG);

  /**
   * True when this is not a production build.
   *
   * Drives the warning at the top. Someone reading a page about how their data
   * is handled deserves to be told when they are looking at a build where
   * sign-in is not real.
   *
   * @returns Whether this build is pointed at production.
   */
  isLocal(): boolean {
    return this.config.environment !== 'production';
  }
}
